### ISSUE TITLE
HTML, CSS,  Javascript

### ISSUE THREAD

**Issue by amisha-28** [amisha-28/Hacktoberfest-20200#1]
You can add any webpage or website, using html, css, javascript

**Comment by IMPrimph** [comment]
@28-2001 
I am interested to do
Can you provide a brief intro about the project

**Comment by Amulya-coder** [comment]
@28-2001 I am also Interested tell me more about it.

**Comment by Shivangi-ch** [comment]
Hi @amisha-28 Can i add my webpage?

**Comment by vanya-24** [comment]
Can i do this? @amisha-28 ,you can check my github profile I've uploaded Shopping Website, Gallery Project and one Web Page too!
https://github.com/vanya-24/Shopping_Website-Shopping Website
https://github.com/vanya-24/Gallery_Project-Gallery Project
https://github.com/vanya-24/WEB_PAGE-Web Page
You can assign it to me! @amisha-28

**Comment by starrohan999** [comment]
hii @amisha-28. I am interested in making web pages. can you please provide more info about it?

**Comment by starrohan999** [comment]
I made a simple desktop application with the help of the Python Tkinter module. can I pull it? 
this my first time in open source.

**Comment by ReoCorreia** [comment]
I'm interested can you assign it to me.

**Comment by starrohan999** [comment]
Yaa sure

**Comment by TechnoPhasePRO** [comment]
@amisha-28 hey, i would like to work on this issue. I have a created a small project using html, css,javascript. Please assign this to me.

**Comment by TechnoPhasePRO** [comment]
@amisha-28 Please check the pull request #20 Made. I have added a dice game using html,css & javascript. Please merge the PR and provide labels to it.

**Comment by kartikagarwal9** [comment]
@amisha-28 I am an experienced web developer, i would love to contribute

**Comment by Shivangi-ch** [comment]
@amisha-28  please review my pr #9 asap . i had made it yesterday.

**Comment by aritrochakraborty29** [comment]
want to contribute

**Comment by adilsp5075** [comment]
i created a bus ticket booking website if u are interested i would like to contribute it
